name: Deploy to ECS

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/docker-ecr.yml'
      - '.github/workflows/deploy-to-ecs.yml'
      - 'app/**'
      - 'terraform/**'
      - '!terraform/README.md'
      - '!app/README.md'

jobs:
  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment
