name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "test"

jobs:
  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets[format('ECS_CLUSTER_NAME_{0}', github.event.inputs.environment)] }} \
            --service ${{ secrets[format('ECS_SERVICE_NAME_{0}', github.event.inputs.environment)] }} \
            --force-new-deployment
