name: Deploy to test

on:
  # Manual trigger via GitHub UI
  workflow_dispatch:

  # Auto-trigger on PR to develop
  pull_request:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to ECS Fargate (test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster "${{ secrets.ECS_CLUSTER_NAME_TEST }}" \
            --service "${{ secrets.ECS_SERVICE_NAME_TEST }}" \
            --force-new-deployment
